# stage 1: install dependencies and build the app
FROM node:18-alpine as build
WORKDIR /todo/fe

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# stage 2: serve the app with nginx server
FROM nginx
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /todo/fe/build /usr/share/nginx/html

EXPOSE 3000
 # CMD ["nginx", "-g", "daemon off;"]