# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create database
      run: PGPASSWORD=password psql -U postgres ./TodoDatabaseDocker.sql

    - name: Install dependencies in back-end folder
      run: npm install
      working-directory: ./back-end

    - name: Install dependencies in front-end folder
      run: npm install
      working-directory: ./front-end

    - name: Run back-end
      run: npm run backend-server

    - name: Run front-end
      run: npm run frontend-server
    

  compose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run docker compose
      run: docker compose up -d --build #use "docker compose" instead of "docker-compose" cuz it's deprecated

    - name: Stop docker-compose
      run: docker compose down -v
